'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');
const C=require('../widgets/wallbox-status/public/widget-controller.js');
const base={chargeState:'2',evState:'plugged_in_charging',chargePower:7400,chargeEnergy:12.6,paused:false,connectionError:false,physicalCharging:true,targetPowerMode:'homey',lastUpdated:1790514000000,stale:false,fault:null};
function view(){return {last:null,states:[],messages:[],render(m){this.last=m;this.states.push(m.state);},setBusy(b){this.busy=b;},message(x){this.messages.push(x);},clearMessage(){}};}
function ctx(handler,opts={}){const calls=[],v=view();const H={api(...args){calls.push(args);return handler(...args);},hapticFeedback(){}};return {calls,v,c:C.create(H,v,{deviceId:'pair-123',...opts})};}
function read(raw,path){return {...raw,...(path.includes('force=true')?{confirmed:true}:{})};}
test('poll uses paired device, no writes and no forced hardware read',async()=>{const x=ctx(async()=>base);await x.c.refresh();assert.equal(x.calls[0][1],'/status?deviceId=pair-123');assert.equal(x.v.last.state,'charging');assert.equal(x.calls.length,1);x.c.destroy();});
test('click captures intent and POSTs directly, then GET force=true',async()=>{let s={...base};const x=ctx(async(method,path,body)=>{if(method==='POST'){s={...s,paused:body.paused,chargePower:0,physicalCharging:false,evState:'plugged_in_paused'};return{success:true};}return read(s,path);});await x.c.refresh();await x.c.act('pause');assert.deepEqual(x.calls.map(x=>x[0]),['GET','POST','GET']);assert.deepEqual(x.calls[1][2],{paused:true,deviceId:'pair-123'});assert.match(x.calls[2][1],/force=true/);assert.equal(x.v.last.state,'paused');assert.equal(x.v.messages.length,0);x.c.destroy();});
test('resume confirms permission and keeps Ready until measured power is positive',async()=>{let s={...base,paused:true,chargePower:0,physicalCharging:false,evState:'plugged_in_paused'};const x=ctx(async(method,path,body)=>{if(method==='POST'){s={...s,paused:body.paused,evState:'plugged_in'};return{success:true};}return read(s,path);});await x.c.refresh();await x.c.act('resume');assert.equal(x.v.last.state,'ready');assert.equal(x.v.messages.length,0);x.c.destroy();});
test('double tap emits one POST',async()=>{const x=ctx(async(method,path)=>{if(method==='POST'){await new Promise(r=>setTimeout(r,15));return{success:true};}return read(base,path);});await x.c.refresh();await Promise.all([x.c.act('pause'),x.c.act('pause')]);assert.equal(x.calls.filter(x=>x[0]==='POST').length,1);x.c.destroy();});
test('stale click cannot invert the user intent',async()=>{let s=base;const x=ctx(async(m,p)=>m==='POST'?{success:true}:read(s,p));await x.c.refresh();s={...base,paused:true,chargePower:0,physicalCharging:false};await x.c.refresh();await x.c.act('pause');assert.equal(x.calls.filter(x=>x[0]==='POST').length,0);x.c.destroy();});
test('GET failure shows offline and never retries a write',async()=>{const x=ctx(async()=>{throw Error('network');});await x.c.refresh();assert.equal(x.v.last.state,'offline');assert.equal(x.v.last.power,null);assert.equal(x.calls.length,1);x.c.destroy();});
test('POST failure is not presented as a success',async()=>{const x=ctx(async method=>{if(method==='POST')throw Error('failed');return base;});await x.c.refresh();await x.c.act('pause');assert.ok(x.v.messages.includes('requestFailed'));assert.equal(x.calls.length,2);assert.equal(x.v.busy,false);x.c.destroy();});
test('GET timeout ignores late telemetry',async()=>{let resolve;const x=ctx(()=>new Promise(r=>{resolve=r;}),{timeoutMs:15});await x.c.refresh();assert.equal(x.v.last.state,'offline');resolve(base);await new Promise(r=>setTimeout(r,5));assert.equal(x.v.last.state,'offline');x.c.destroy();});
test('destroy after POST prevents a subsequent confirmation request',async()=>{let finish;const x=ctx(m=>m==='POST'?new Promise(r=>{finish=r;}):Promise.resolve(base));await x.c.refresh();const p=x.c.act('pause');await new Promise(r=>setImmediate(r));x.c.destroy();finish({success:true});await p;assert.equal(x.calls.length,2);});
test('normal refreshes coalesce',async()=>{const x=ctx(async()=>{await new Promise(r=>setTimeout(r,5));return base;});await Promise.all([x.c.refresh(),x.c.refresh(),x.c.refresh()]);assert.equal(x.calls.length,1);x.c.destroy();});
test('readback failure after ACK is unconfirmed, no old charging animation',async()=>{const x=ctx(async(m,p)=>{if(m==='POST')return{success:true};if(p.includes('force=true'))throw Error('network');return base;});await x.c.refresh();await x.c.act('pause');assert.equal(x.v.last.state,'stale');assert.ok(x.v.messages.includes('awaiting'));assert.equal(x.calls.filter(x=>x[0]==='POST').length,1);x.c.destroy();});
test('confirmed=true alone does not claim Pause if permission did not change',async()=>{const x=ctx(async(m,p)=>m==='POST'?{success:true}:read(base,p));await x.c.refresh();await x.c.act('pause');assert.ok(x.v.messages.includes('awaiting'));assert.equal(x.v.last.state,'charging');x.c.destroy();});
test('confirmed=false remains unconfirmed',async()=>{const x=ctx(async(m,p)=>m==='POST'?{success:true}:{...base,...(p.includes('force=true')?{confirmed:false}: {})});await x.c.refresh();await x.c.act('pause');assert.equal(x.v.last.state,'stale');assert.ok(x.v.messages.includes('awaiting'));x.c.destroy();});
test('slow pre-command poll does not block Stop and cannot overwrite confirmation',async()=>{let resolveSlow,n=0;const x=ctx(async(m,p)=>{if(m==='POST')return{success:true};if(p.includes('force=true'))return read({...base,paused:true,chargePower:0,physicalCharging:false},p);if(n++===0)return base;return new Promise(r=>{resolveSlow=r;});});await x.c.refresh();const slow=x.c.refresh();await new Promise(r=>setImmediate(r));await x.c.act('pause');assert.equal(x.v.last.state,'paused');resolveSlow(base);await slow;assert.equal(x.v.last.state,'paused');x.c.destroy();});
test('late pre-command GET failure cannot turn a confirmed command Offline',async()=>{let rejectSlow,n=0;const x=ctx(async(m,p)=>{if(m==='POST')return{success:true};if(p.includes('force=true'))return read({...base,paused:true,chargePower:0,physicalCharging:false},p);if(n++===0)return base;return new Promise((_,r)=>{rejectSlow=r;});});await x.c.refresh();const slow=x.c.refresh();await new Promise(r=>setImmediate(r));await x.c.act('pause');rejectSlow(Error('old network failure'));await slow;assert.equal(x.v.last.state,'paused');x.c.destroy();});
test('Homey target rejection does not change ownership or invent a target',async()=>{const x=ctx(async m=>{if(m==='POST')throw Error('positive achievable Homey target required');return {...base,paused:true,chargePower:0,physicalCharging:false};});await x.c.refresh();await x.c.act('resume');assert.equal(x.v.last.owner,'homey');assert.ok(x.v.messages.includes('targetRequired'));assert.deepEqual(x.calls.filter(c=>c[0]==='POST').map(c=>c[2]),[{paused:false,deviceId:'pair-123'}]);x.c.destroy();});
test('retry requests fresh status only; never replays the command',async()=>{const x=ctx(async(m,p)=>read(base,p));await x.c.refresh();await x.c.act('refresh');assert.deepEqual(x.calls.map(c=>c[0]),['GET','GET']);assert.match(x.calls[1][1],/force=true/);x.c.destroy();});
test('selection errors are not confused with wallbox network failures',async()=>{const x=ctx(async()=>{throw Error('The selected wallbox is unavailable. Please select it again.');});await x.c.refresh();assert.equal(x.v.last.state,'selection');x.c.destroy();});
test('widget cannot write before any status is known',async()=>{const x=ctx(async()=>base);await x.c.act('resume');assert.equal(x.calls.length,0);x.c.destroy();});
test('stale Last known Stop is still a fixed pause write',async()=>{const x=ctx(async(m,p)=>m==='POST'?{success:true}:read({...base,stale:true},p));await x.c.refresh();await x.c.act('pause');assert.equal(x.calls.filter(c=>c[0]==='POST').length,1);assert.equal(x.calls.find(c=>c[0]==='POST')[2].paused,true);x.c.destroy();});
