'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');
const C=require('../widgets/wallbox-status/public/widget-core.js');
const sample={chargeState:'2',evState:'plugged_in_charging',chargePower:7400,chargeEnergy:12.6,paused:false,connectionError:false,physicalCharging:true,targetPowerMode:'homey',lastUpdated:1790514000000,stale:false,fault:null};
test('PR3 Homey ownership is separate from charge state',()=>{const m=C.normalizeStatus(sample);assert.equal(m.owner,'homey');assert.equal(m.state,'charging');});
test('all six existing V2C strategies display Wallbox, not a solar claim',()=>{for(const mode of ['v2c_timed_on','v2c_timed_off','v2c_fv_exclusive','v2c_fv_min','v2c_grid_fv','v2c_no_charge'])assert.equal(C.normalizeStatus({...sample,targetPowerMode:mode}).owner,'wallbox');});
test('unknown owner never defaults to Wallbox or Homey',()=>{for(const mode of [null,undefined,'device','v2c_future','2',{},true])assert.equal(C.normalizeStatus({...sample,targetPowerMode:mode}).owner,null);});
test('pause does not change Homey ownership',()=>{const m=C.normalizeStatus({...sample,paused:true,chargePower:0,physicalCharging:false});assert.equal(m.owner,'homey');assert.equal(m.state,'paused');});
test('offline or stale samples do not claim current owner',()=>{for(const changes of [{connectionError:true},{stale:true},{lastUpdated:null},{confirmed:false}])assert.equal(C.normalizeStatus({...sample,...changes}).owner,null);});
test('EV charging permission with zero power is Ready, not animated charging',()=>{assert.equal(C.normalizeStatus({...sample,chargePower:0,physicalCharging:false}).state,'ready');});
test('positive power with a ready EV state still shows measured charging',()=>{assert.equal(C.normalizeStatus({...sample,chargeState:'1',evState:'plugged_in'}).state,'charging');});
test('explicit null EV state never collapses to disconnected legacy code',()=>{assert.equal(C.normalizeStatus({...sample,chargeState:'0',evState:null}).state,'unknown');});
test('discharging is not rendered as forward energy flow',()=>{assert.equal(C.normalizeStatus({...sample,evState:'plugged_in_discharging'}).state,'unknown');});
test('inconsistent or missing measured power never animates a charging report',()=>{for(const power of [null,'',true,-1,NaN,Infinity,0])assert.notEqual(C.normalizeStatus({...sample,chargePower:power}).state,'charging');});
test('nullable permission remains unknown despite valid power',()=>{assert.equal(C.normalizeStatus({...sample,paused:null}).state,'unknown');});
test('faults F/E/D are distinct from transport loss and suppress resume',()=>{for(const code of [4,5,6]){const m=C.normalizeStatus({...sample,fault:{state:code,description:'Primary fault'},paused:true});assert.equal(m.state,'fault');assert.equal(m.faultCode,String(code));assert.notEqual(m.action,'resume');}});
test('inverter diagnostics do not become a primary fault',()=>{assert.equal(C.normalizeStatus({...sample,slaveError:'04'}).state,'charging');});
test('timer and lock metadata do not invent Scheduled or change owner',()=>{const m=C.normalizeStatus({...sample,chargePower:0,physicalCharging:false,timerActive:true,locked:true});assert.equal(m.state,'ready');assert.equal(m.owner,'homey');assert.equal(m.action,'pause');});
test('stale telemetry retains last values but not charging motion',()=>{const m=C.normalizeStatus({...sample,stale:true});assert.equal(m.state,'stale');assert.equal(m.power,7.4);assert.equal(m.energy,12.6);assert.equal(m.quality,'last-known');});
test('primary fault remains visible when a later sample is stale',()=>{assert.equal(C.normalizeStatus({...sample,stale:true,fault:{state:4,description:'F'}}).state,'fault');});
test('freshness without timestamp or stale flag is not asserted',()=>{for(const change of [{lastUpdated:null},{stale:undefined}])assert.equal(C.normalizeStatus({...sample,...change}).state,'stale');});
test('stale data can still issue a fixed Stop but not Resume',()=>{const m=C.normalizeStatus({...sample,stale:true});assert.deepEqual(C.commandFor('pause',m),{paused:true});assert.throws(()=>C.commandFor('resume',{...m,paused:true}),/unavailable/);});
test('confirmation is fresh telemetry PLUS requested permission, not success alone',()=>{assert.equal(C.commandConfirmed({...sample,confirmed:true},true),false);assert.equal(C.commandConfirmed({...sample,confirmed:true,paused:true},true),false);assert.equal(C.commandConfirmed({...sample,confirmed:true,paused:true,physicalCharging:false,chargePower:0},true),true);});
test('Resume confirmation at zero power only confirms permission, and remains Ready',()=>{const r={...sample,confirmed:true,physicalCharging:false,chargePower:0};assert.equal(C.commandConfirmed(r,false),true);assert.equal(C.normalizeStatus(r).state,'ready');});
test('confirmation false, stale, fault, missing timestamp never confirm commands',()=>{for(const c of [{confirmed:false},{stale:true},{fault:{state:4}},{lastUpdated:null}])assert.equal(C.commandConfirmed({...sample,confirmed:true,...c},false),false);});
test('autocomplete object uses exact pairing data ID',()=>{assert.equal(C.selectedDeviceId({device_id:{id:'pair-123',name:'Garage'}}),'pair-123');});
test('observed PR string selection is also supported',()=>{assert.equal(C.selectedDeviceId({device_id:'pair-123'}),'pair-123');});
test('invalid explicit selection never silently falls back to another device',()=>{for(const id of ['', ' ', {}, {name:'Garage'}, {id:''}, 123, ['id']])assert.throws(()=>C.selectedDeviceId({device_id:id}),/selection/);});
test('unset legacy selection stays null for PR3 single-device-only backend fallback',()=>{assert.equal(C.selectedDeviceId({}),null);assert.equal(C.selectedDeviceId({device_id:null}),null);});
